remote_theme: pmarsceill/just-the-docs
# theme: "just-the-docs" #enabling it when using github page might lead to failure
markdown: kramdown

color_scheme: dark
# color_scheme: beut

# Footer "Edit this page on GitHub" link text
gh_edit_link: false # show or hide edit this page link
# gh_edit_link_text: "View on =^._.^= ∫"
# gh_edit_repository: "https://github.com/dlccyes/blog" # the github URL for your repo
# gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
